/**
 * Splits index.legacy.html → Vite src/ layout.
 * Preserves behavior by registering legacy functions on window for inline handlers.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const legacyPath = path.join(root, 'index.legacy.html');
const indexPath = path.join(root, 'index.html');
const sourcePath = fs.existsSync(legacyPath) ? legacyPath : indexPath;

const html = fs.readFileSync(sourcePath, 'utf8');

if (!fs.existsSync(legacyPath) && sourcePath === indexPath) {
  fs.copyFileSync(indexPath, legacyPath);
  console.log('Backed up index.html → index.legacy.html');
}

const cssMatch = html.match(/<style>([\s\S]*?)<\/style>/);
if (!cssMatch) throw new Error('Could not extract <style> block');
const css = cssMatch[1];

const bodyMatch = html.match(/<body style="position:relative">([\s\S]*?)<script>\s*'use strict';/);
if (!bodyMatch) throw new Error('Could not extract <body> HTML');
const bodyBeforeScripts = bodyMatch[1];

const tailMatch = html.match(/<!-- Barra inferior móvil -->([\s\S]*?)<script>if\(typeof _mobileUiRefresh/);
if (!tailMatch) throw new Error('Could not extract mobile nav HTML');
const bodyInner = `${bodyBeforeScripts.trim()}\n\n<!-- Barra inferior móvil -->${tailMatch[1].trim()}`;

const scriptsMatch = html.match(/<script>\s*'use strict';([\s\S]*?)<\/script>\s*<script>\s*\/\/ ── FIREBASE AUTH/);
if (!scriptsMatch) throw new Error('Could not extract core script');
const coreScript = scriptsMatch[1];

const firebaseMatch = html.match(/\/\/ ── FIREBASE AUTH \+ ADMIN ──[\s\S]*?\n([\s\S]*?)<\/script>\s*<!-- Barra inferior móvil -->/);
if (!firebaseMatch) throw new Error('Could not extract firebase script');
const firebaseScript = `// ── FIREBASE AUTH + ADMIN ──────────────────────────────────────────────────\n${firebaseMatch[1]}`;

function collectFunctionNames(js) {
  const names = new Set();
  const re = /(?:^|\n)(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/g;
  let m;
  while ((m = re.exec(js)) !== null) names.add(m[1]);
  return names;
}

function collectInlineHandlerNames(bodyHtml) {
  const names = new Set();
  const re = /on(?:click|change|input|keydown)="(?:[^"]*?)(?:^|[\s;(])([A-Za-z_$][\w$]*)\s*\(/g;
  let m;
  while ((m = re.exec(bodyHtml)) !== null) names.add(m[1]);
  if (bodyHtml.includes("$('") || bodyHtml.includes('$("')) names.add('$');
  return names;
}

function collectTopLevelBindings(js) {
  const names = collectFunctionNames(js);
  const re = /(?:^|\n)(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=/g;
  let m;
  while ((m = re.exec(js)) !== null) names.add(m[1]);
  return names;
}

const CORE_EXTRA_GLOBALS = ['T', '$', 'tabs', 'activeTabId', 'eh', 'ejs'];
const FIREBASE_EXTRA_GLOBALS = ['_fbDb', '_fbStorage', '_fbAuth', '_fbFns'];

function buildGlobalsBlock(names) {
  const lines = [...new Set(names)].sort().map((n) => `  ${n},`);
  return [
    '',
    '// ── Inline handler globals (auto-generated by scripts/split-phase0.mjs) ──',
    'const __miradorGlobals = {',
    ...lines,
    '};',
    'for (const [key, val] of Object.entries(__miradorGlobals)) {',
    '  if (val !== undefined) window[key] = val;',
    '}',
    '',
  ].join('\n');
}

function buildFirebaseRuntimeExports() {
  return [
    '// Live Firebase refs for E2E tests (getters track auth state)',
    'window._fbDb = _fbDb;',
    'window._fbStorage = _fbStorage;',
    'window._fbAuth = _fbAuth;',
    'Object.defineProperty(window, "_fbUser", { get() { return _fbUser; }, configurable: true });',
    'Object.defineProperty(window, "_fbUserRole", { get() { return _fbUserRole; }, configurable: true });',
    '',
  ].join('\n');
}

const coreBindings = collectTopLevelBindings(coreScript);
const firebaseBindings = collectTopLevelBindings(firebaseScript);
const handlerNames = collectInlineHandlerNames(bodyInner);

const coreGlobals = [
  ...coreBindings,
  ...[...handlerNames].filter((n) => coreBindings.has(n)),
  ...CORE_EXTRA_GLOBALS.filter((n) => coreBindings.has(n)),
];
const firebaseGlobals = [
  ...firebaseBindings,
  ...[...handlerNames].filter((n) => firebaseBindings.has(n)),
  ...FIREBASE_EXTRA_GLOBALS.filter((n) => firebaseBindings.has(n)),
];
const allGlobalNames = [...new Set([...coreGlobals, ...firebaseGlobals])].sort();

const coreOut = ["'use strict';", '', coreScript.trim(), buildGlobalsBlock(coreGlobals)].join('\n');
const firebaseOut = [
  "'use strict';",
  '',
  '// Depends on core globals (tabs, T, loadSheet, etc.)',
  firebaseScript.trim(),
  buildGlobalsBlock(firebaseGlobals),
  buildFirebaseRuntimeExports(),
].join('\n');

for (const d of ['src/styles', 'src/app', 'src/services']) {
  fs.mkdirSync(path.join(root, d), { recursive: true });
}

fs.writeFileSync(path.join(root, 'src', 'styles', 'main.css'), css.trim() + '\n');
fs.writeFileSync(path.join(root, 'src', 'app', 'core.js'), coreOut + '\n');
fs.writeFileSync(path.join(root, 'src', 'services', 'firebase-app.js'), firebaseOut + '\n');

function stripLegacyReactShell(bodyHtml) {
  return bodyHtml
    .replace(/<div id="topbar">[\s\S]*?<input type="file" id="file-input"[\s\S]*?<\/div>\s*\n?/, '')
    .replace(/<div id="tabs-bar">[\s\S]*?<\/div>\s*\n?/, '')
    .replace(/<div id="stats-bar">[\s\S]*?<\/div>\s*\n?/, '<div id="stats-bar-root"></div>\n')
    .replace(/<div id="chips-bar">[\s\S]*?<\/div>\s*\n?/, '<div id="chips-bar-root"></div>\n')
    .replace(/<div id="searchbar">[\s\S]*?<\/div>\s*\n?/, '<div id="searchbar-root"></div>\n')
    .replace(/<!-- Barra filtros activos móvil -->[\s\S]*?<div id="mobile-active-bar">[\s\S]*?<\/div>\s*\n?/, '<div id="mobile-active-bar-root"></div>\n')
    .replace(/<!-- Panel Mis Documentos -->[\s\S]*?<div id="docs-panel">[\s\S]*?<\/div>\s*\n?/, '<div id="docs-panel-root"></div>\n')
    .replace(/<div id="sidebar">[\s\S]*?<\/div>\s*\n(?=\s*<div id="data-area)/, '<div id="sidebar-root"></div>\n')
    .replace(/<div id="data-area">[\s\S]*?<div id="table-wrap">[\s\S]*?<\/div>\s*\n\s*<\/div>\s*\n?/, '<div id="data-area-root"></div>\n')
    .replace(/<!-- ── PILLS VIEW ──[\s\S]*?<div id="pills-view">[\s\S]*?<\/div>\s*\n(?=\s*<\/div>)/, '<div id="pills-view-root"></div>\n')
    .replace(/<div id="statusbar">[\s\S]*?<\/div>\s*\n?/, '<div id="statusbar-root"></div>\n')
    .replace(/<div id="detail-overlay">[\s\S]*?<div id="pills-ficha-overlay">[\s\S]*?<\/div>\s*\n\s*<\/div>\s*\n?/, '<div id="overlays-root"></div>\n')
    .replace(/<!-- Barra inferior móvil -->[\s\S]*?<nav id="mobile-bnav"[\s\S]*?<\/nav>\s*\n?/, '<div id="mobile-bnav-root"></div>\n')
    .replace(/<!-- Panel filtros avanzados móvil -->[\s\S]*?<div id="mobile-filter-overlay">[\s\S]*?<\/div>\s*\n?/, '<div id="mobile-filter-root"></div>\n')
    .replace(/<button id="viewport-restore-btn"[\s\S]*?<\/button>\s*\n?/, '')
    .trim();
}

const viteIndex = `<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes"/>
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"/>
<script>
(function(){
  var BUILD='20260611-overlays-react-v1', k='mirador_build_v';
  var prev=localStorage.getItem(k);
  if(prev&&prev!==BUILD){ localStorage.setItem(k,BUILD); location.reload(); return; }
  localStorage.setItem(k,BUILD);
})();
</script>
<!-- Firebase SDK (compat — modular SDK in Phase 1) -->
<script src="https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/10.12.0/firebase-auth-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/10.12.0/firebase-storage-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/10.12.0/firebase-functions-compat.js"></script>
<title>Mirador — análisis de planillas</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/4.3.0/exceljs.min.js"></script>
<link rel="stylesheet" href="/src/styles/main.css"/>
</head>
<body style="position:relative">
<div id="login-screen">
  <div id="login-root"></div>
</div>

<div id="topbar-root"></div>

<div id="tabs-bar-root"></div>

${stripLegacyReactShell(bodyInner)}

<script type="module" src="/src/main.jsx"></script>
</body>
</html>
`;

fs.writeFileSync(indexPath, viteIndex);

fs.writeFileSync(
  path.join(root, 'src', 'main.jsx'),
  `import './styles/main.css';
import { mountAppShell } from './react/mount-app.jsx';

mountAppShell();

async function boot() {
  await new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r)));
  await import('./app/core.js');
  await import('./services/firebase-app.js');
  if (typeof window._mobileUiRefresh === 'function') {
    window._mobileUiRefresh();
  }
}

boot();
`
);

console.log(`Phase 0 split complete:
  src/styles/main.css            (${css.trim().length} chars)
  src/app/core.js                (${coreBindings.size} bindings)
  src/services/firebase-app.js   (${firebaseBindings.size} bindings)
  window globals registered:     ${allGlobalNames.length}
  index.html → Vite entry`);
